import {onAuthStateChanged,signOut} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import {collection,query,where,getDocs,doc,updateDoc,serverTimestamp} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import {auth,db} from "./firebase-config.js";
let org=null,all=[];const $=id=>document.getElementById(id);const list=$("schemeList");
function esc(v){return String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));}
function status(s){return `<span class="badge ${s}">${s.replace(/_/g," ").toUpperCase()}</span>`}
function render(){const q=$("search").value.toLowerCase(),f=$("filter").value;const data=all.filter(x=>(!f||x.status===f)&&(!q||`${x.subject} ${x.className} ${x.createdByName}`.toLowerCase().includes(q)));list.innerHTML=data.map(x=>`<div class="card"><div class="head"><div><h2>${esc(x.subject)} — ${esc(x.className)}</h2><p>${esc(x.term)} • ${esc(x.academicYear)} • Submitted by ${esc(x.createdByName)}</p></div>${status(x.status)}</div><details><summary>View complete scheme</summary><div class="tablewrap"><table><thead><tr><th>Week</th><th>Topic</th><th>Content</th><th>Objective</th><th>Activities</th><th>Materials</th><th>Assessment</th></tr></thead><tbody>${(x.rows||[]).map(r=>`<tr><td>${esc(r.week)}</td><td>${esc(r.topic)}</td><td>${esc(r.content)}</td><td>${esc(r.objective)}</td><td>${esc(r.activities)}</td><td>${esc(r.materials)}</td><td>${esc(r.assessment)}</td></tr>`).join("")}</tbody></table></div>${x.attachment?.url?`<p><a target="_blank" href="${esc(x.attachment.url)}">📎 Open attached ${esc(x.attachment.name)}</a></p>`:""}</details><div class="actions"><button class="approve" data-action="approved" data-id="${x.id}">✓ Approve / Publish</button><button class="changes" data-action="changes_requested" data-id="${x.id}">↺ Request Changes</button><button class="reject" data-action="rejected" data-id="${x.id}">✕ Reject</button></div>${x.adminComment?`<p class="comment"><b>Administrator:</b> ${esc(x.adminComment)}</p>`:""}</div>`).join("")||'<div class="card">No schemes match the current filter.</div>';}
async function load(){const s=await getDocs(query(collection(db,"schemesOfWork"),where("organizationId","==",org.id)));all=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.updatedAt?.seconds||b.createdAt?.seconds||0)-(a.updatedAt?.seconds||a.createdAt?.seconds||0));$("count").textContent=`${all.length} scheme(s)`;render();}
list.addEventListener("click",async e=>{const b=e.target.closest("button[data-id]");if(!b)return;const comment=prompt(b.dataset.action==="approved"?"Optional approval note:":"What should the Form Master know?");if(comment===null&&b.dataset.action!=="approved")return;await updateDoc(doc(db,"schemesOfWork",b.dataset.id),{status:b.dataset.action,adminComment:comment||"",reviewedByUid:auth.currentUser.uid,reviewedAt:serverTimestamp()});await load();});$("search").oninput=render;$("filter").onchange=render;$("logout").onclick=()=>signOut(auth);
onAuthStateChanged(auth,async u=>{if(!u)return location.href="login.html";try{const s=await getDocs(query(collection(db,"organizations"),where("ownerUid","==",u.uid)));if(s.empty)throw Error("Administrator organization not found.");org={id:s.docs[0].id,...s.docs[0].data()};$("adminName").textContent=org.adminName||u.email||"Administrator";$("organizationName").textContent=org.organizationName||org.name||"Organization";await load();}catch(e){list.innerHTML=`<div class="card error">${esc(e.message)}</div>`;}});
