/* VIRELLO TECHNOLOGIES - SCHEME OF WORK */
import { onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import { collection, query, where, getDocs, addDoc, doc, updateDoc, serverTimestamp, orderBy } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import { auth, db } from "./firebase-config.js";
import { CLOUDINARY_CLOUD_NAME, CLOUDINARY_UPLOAD_PRESET } from "./cloudinary-config.js";

let currentUser=null,currentTeacher=null,currentOrganization=null,editingId=null,rows=[];
const $=id=>document.getElementById(id);
const tableBody=$("schemeBody"), message=$("message"), statusBox=$("statusBox"), previous=$("previousScheme");

function esc(v){return String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));}
function toast(t,ok=true){message.textContent=t;message.className=ok?"message success":"message error";}
function teacherName(){return currentTeacher?.fullName||currentTeacher?.name||currentTeacher?.staffName||currentUser?.email||"Form Master";}
function addRow(data={}){rows.push({...data});renderRows();}
function renderRows(){tableBody.innerHTML=rows.map((r,i)=>`<tr><td><input value="${esc(r.week)}" data-i="${i}" data-k="week" placeholder="1"></td><td><input value="${esc(r.topic)}" data-i="${i}" data-k="topic" placeholder="Topic / Unit"></td><td><textarea data-i="${i}" data-k="content">${esc(r.content)}</textarea></td><td><textarea data-i="${i}" data-k="objective">${esc(r.objective)}</textarea></td><td><textarea data-i="${i}" data-k="activities">${esc(r.activities)}</textarea></td><td><textarea data-i="${i}" data-k="materials">${esc(r.materials)}</textarea></td><td><textarea data-i="${i}" data-k="assessment">${esc(r.assessment)}</textarea></td><td><button type="button" class="remove" data-remove="${i}">×</button></td></tr>`).join("");}
function sync(){tableBody.querySelectorAll("[data-k]").forEach(el=>rows[Number(el.dataset.i)][el.dataset.k]=el.value);}

tableBody.addEventListener("input",sync); tableBody.addEventListener("click",e=>{if(e.target.dataset.remove){rows.splice(Number(e.target.dataset.remove),1);renderRows();}});
$("addWeek").onclick=()=>addRow({week:rows.length+1});
$("saveDraft").onclick=()=>save("draft");
$("submitScheme").onclick=()=>save("submitted");
$("logout").onclick=()=>signOut(auth);
$("newScheme").onclick=()=>{editingId=null;rows=[];renderRows();$("schemeForm").reset();statusBox.textContent="New scheme";};
$("copyPrevious").onclick=async()=>{const id=previous.value;if(!id)return toast("Select a previous scheme first.",false);const snap=await getDocs(query(collection(db,"schemesOfWork"),where("organizationId","==",currentOrganization.id)));const d=snap.docs.find(x=>x.id===id);if(!d)return;const x=d.data();$("subject").value=x.subject||"";$("className").value=x.className||"";$("term").value=x.term||"";$("academicYear").value=x.academicYear||"";$("weeks").value=x.weeks||"";rows=(x.rows||[]).map(r=>({...r}));editingId=null;statusBox.textContent="Copied from previous scheme — edit before saving/submitting";renderRows();toast("Previous scheme copied. You can now edit it.");};

async function findTeacher(){let s=await getDocs(query(collection(db,"staff"),where("userUid","==",currentUser.uid)));if(s.empty)s=await getDocs(query(collection(db,"staff"),where("uid","==",currentUser.uid)));if(s.empty&&currentUser.email)s=await getDocs(query(collection(db,"staff"),where("email","==",currentUser.email)));if(s.empty)throw Error("Form Master staff profile not found.");currentTeacher={id:s.docs[0].id,...s.docs[0].data()};}
async function findOrg(){let id=currentTeacher.organizationId;let s=id?await getDocs(query(collection(db,"organizations"),where("__name__","==",id))):{empty:true};if(s.empty&&currentTeacher.ownerUid)s=await getDocs(query(collection(db,"organizations"),where("ownerUid","==",currentTeacher.ownerUid)));if(s.empty)throw Error("Your organization could not be found.");currentOrganization={id:s.docs[0].id,...s.docs[0].data()};$("teacherName").textContent=teacherName();$("organizationName").textContent=currentOrganization.organizationName||currentOrganization.name||"Organization";}
async function loadPrevious(){previous.innerHTML='<option value="">Select previous scheme...</option>';const s=await getDocs(query(collection(db,"schemesOfWork"),where("organizationId","==",currentOrganization.id)));s.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.createdByUid===currentUser.uid||x.status==="approved").sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)).forEach(x=>{const o=document.createElement("option");o.value=x.id;o.textContent=`${x.subject||"Scheme"} — ${x.className||"Class"} — ${x.term||"Term"} — ${x.academicYear||"Year"} (${x.status})`;previous.appendChild(o);});}
async function save(status){sync();if(!$("subject").value.trim()||!$("className").value.trim()||!$("term").value.trim()||!$("academicYear").value.trim()||!rows.length)return toast("Complete the subject, class, term, academic year, and at least one week.",false);const file=$("schemeFile").files[0];let attachment=null;if(file){const ok=["application/pdf","application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/msword"].includes(file.type)||/\.(pdf|doc|docx)$/i.test(file.name);if(!ok)return toast("Please attach a PDF, DOC, or DOCX file.",false);if(file.size>10*1024*1024)return toast("Attachment must be 10 MB or smaller.",false);if(!CLOUDINARY_CLOUD_NAME || !CLOUDINARY_UPLOAD_PRESET || CLOUDINARY_CLOUD_NAME.includes("YOUR_") || CLOUDINARY_UPLOAD_PRESET.includes("YOUR_"))throw Error("File upload is not configured yet. Add your Cloudinary Cloud Name and unsigned Upload Preset in js/cloudinary-config.js, or remove the attachment and submit the scheme without a file.");
const formData=new FormData();formData.append("file",file);formData.append("upload_preset",CLOUDINARY_UPLOAD_PRESET);formData.append("folder",`virello/schemes-of-work/${currentOrganization.id}`);formData.append("context",`organizationId=${currentOrganization.id}|createdByUid=${currentUser.uid}|teacher=${teacherName()}|schemeType=scheme-of-work`);
const response=await fetch(`https://api.cloudinary.com/v1_1/${encodeURIComponent(CLOUDINARY_CLOUD_NAME)}/raw/upload`,{method:"POST",body:formData});
const result=await response.json();if(!response.ok||!result.secure_url)throw Error(result.error?.message||"The file upload failed. Please check your Cloudinary settings and try again.");
attachment={name:file.name,size:file.size,type:file.type,url:result.secure_url,path:result.public_id||"",provider:"cloudinary"};}
const data={organizationId:currentOrganization.id,subject:$("subject").value.trim(),className:$("className").value.trim(),term:$("term").value.trim(),academicYear:$("academicYear").value.trim(),weeks:Number($("weeks").value)||rows.length,rows,createdByUid:currentUser.uid,createdByStaffId:currentTeacher.id,createdByName:teacherName(),status,updatedAt:serverTimestamp()};if(attachment)data.attachment=attachment;if(!editingId){data.createdAt=serverTimestamp();editingId=(await addDoc(collection(db,"schemesOfWork"),data)).id;}else await updateDoc(doc(db,"schemesOfWork",editingId),data);statusBox.textContent=status==="draft"?"Saved as Draft":"Submitted to Administrator";toast(status==="draft"?"Scheme saved as draft.":"Scheme submitted to the administrator for review.");await loadPrevious();}

onAuthStateChanged(auth,async u=>{if(!u)return location.href="form-master-login.html";currentUser=u;try{await findTeacher();if(currentTeacher.isFormMaster!==true&&String(currentTeacher.role||"").toLowerCase()!=="form master")throw Error("This account is not registered as a Form Master.");await findOrg();await loadPrevious();for(let i=1;i<=13;i++)addRow({week:i});}catch(e){toast(e.message,false);}});
