import {auth,db,onAuthStateChanged,signOut,collection,query,where,getDocs,addDoc,doc,updateDoc,deleteDoc,serverTimestamp,loadClasses,loadTeachers,getProfile,getOrganization,esc,currentAcademicYear,DAYS,showToast,injectStyles,teacherName} from './virello-academic-core.js';
injectStyles();let user,profile,org,classes=[],teachers=[],entries=[],editing=null;
const $=id=>document.getElementById(id);
async function load(){entries=(await getDocs(query(collection(db,'timetableEntries'),where('organizationId','==',org.id)))).docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.academicYear===$('year').value&&x.term===$('term').value&&x.classId===$('classId').value);render();}
function render(){const by={};entries.forEach(e=>(by[e.day]??=[]).push(e));const times=[...new Set(entries.map(e=>`${e.startTime}-${e.endTime}`))].sort();$('grid').innerHTML=times.length?times.map(t=>`<tr><th>${esc(t)}</th>${DAYS.map(d=>`<td>${(by[d]||[]).filter(e=>`${e.startTime}-${e.endTime}`===t).map(e=>`<div class="slot"><strong>${esc(e.subject)}</strong><span>${esc(e.teacherName||'No teacher')}</span><span>${esc(e.room||'')}</span></div>`).join('')}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="6" class="va-empty">No timetable entries yet.</td></tr>`;entries.sort((a,b)=>(DAYS.indexOf(a.day)-DAYS.indexOf(b.day))||a.startTime.localeCompare(b.startTime));$('entries').innerHTML=entries.length?entries.map(e=>`<tr><td>${esc(e.day)}</td><td>${esc(e.startTime)}–${esc(e.endTime)}</td><td>${esc(e.subject)}</td><td>${esc(e.teacherName||'')}</td><td>${esc(e.room||'')}</td><td><button class="va-btn secondary" data-edit="${e.id}">Edit</button> <button class="va-btn danger" data-del="${e.id}">Delete</button></td></tr>`).join(''):`<tr><td colspan="6" class="va-empty">No entries.</td></tr>`;}
function fill(){ $('classId').innerHTML=classes.map(c=>`<option value="${c.id}">${esc(c.className||c.name)}</option>`).join('');$('teacherId').innerHTML=`<option value="">No teacher</option>`+teachers.map(t=>`<option value="${t.id}">${esc(teacherName(t))}</option>`).join('');$('day').innerHTML=DAYS.map(d=>`<option>${d}</option>`).join('');$('year').value=currentAcademicYear();}
$('classId').onchange=load;$('term').onchange=load;$('year').onchange=load;$('refresh').onclick=load;$('cancel').onclick=()=>{editing=null;$('save').textContent='Add to Timetable';$('cancel').style.display='none';};
$('save').onclick=async()=>{try{const classObj=classes.find(c=>c.id===$('classId').value), teacher=teachers.find(t=>t.id===$('teacherId').value);const data={organizationId:org.id,classId:classObj.id,className:classObj.className||classObj.name,academicYear:$('year').value,term:$('term').value,day:$('day').value,startTime:$('start').value,endTime:$('end').value,subject:$('subject').value.trim(),teacherId:teacher?.id||'',teacherName:teacherName(teacher),room:$('room').value.trim(),label:$('label').value.trim(),notes:$('notes').value.trim(),updatedAt:serverTimestamp()};if(!data.subject)throw Error('Enter a subject.');if(editing)await updateDoc(doc(db,'timetableEntries',editing),data);else{data.createdAt=serverTimestamp();data.createdBy=user.uid;await addDoc(collection(db,'timetableEntries'),data)}showToast(editing?'Timetable entry updated.':'Timetable entry added.');editing=null;$('save').textContent='Add to Timetable';$('cancel').style.display='none';$('subject').value='';$('room').value='';$('label').value='';$('notes').value='';await load()}catch(e){showToast(e.message,'error')}};
$('entries').onclick=async e=>{const edit=e.target.dataset.edit,del=e.target.dataset.del;if(edit){const x=entries.find(v=>v.id===edit);editing=x.id;$('classId').value=x.classId;$('year').value=x.academicYear;$('term').value=x.term;$('day').value=x.day;$('start').value=x.startTime;$('end').value=x.endTime;$('subject').value=x.subject;$('teacherId').value=x.teacherId||'';$('room').value=x.room||'';$('label').value=x.label||'';$('notes').value=x.notes||'';$('save').textContent='Save Changes';$('cancel').style.display='inline-block';window.scrollTo({top:0,behavior:'smooth'})}if(del&&confirm('Delete this timetable entry?')){await deleteDoc(doc(db,'timetableEntries',del));showToast('Entry deleted.');load()}};
$('logout').onclick=()=>signOut(auth).then(()=>location.href='login.html');
onAuthStateChanged(auth,async u=>{if(!u)return location.href='login.html';try{user=u;profile=await getProfile(u);org=await getOrganization(profile,u);if(!org)throw Error('Organization not found.');$('school').textContent=org.organizationName||'Your School';classes=await loadClasses(org.id);teachers=await loadTeachers(org.id);fill();await load()}catch(e){showToast(e.message,'error')}});
